# Conclusion {#ch6}

## Other packages
There are many more other packages for exploring and modeling spatial variability in field trials. Some other useful packages available on CRAN:

|package------|usage---------|
| Mcspatial | nonparametric spatial analysis |
|ngspatial | spatial models with a focus on generalised linear models |
|spaMM  | correlated error modes and generalised linear models |
|spANOVA | spatial analysis for field trials |

## Final recommendations

There is no denying that considerable work is needed to develop suitable R functions so researchers can routinely incorporate spatial covariance into field trial analysis. Many current tools are unwieldy to use and have insufficient options to support variety trial analysis. 

Unti this situation is improved, it is probably wisest to focus on using spatial models that are well-supported at this time. Any of the options implemented in the **nlme** package (or that work with that package) are decent choices with excellent support for extracting least-squares means, running ANOVA, and standard model diagnsotics. Furthermore, **nlme** supports generalised linear models. 

Doing something to contol for spatial auto-correlation is highly likely to improve the accuracy and precision of variety estimates and is recommended over doing nothing. 

